# Generated by Django 2.1.1 on 2018-09-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(default='1537-676705-9871', max_length=16),
        ),
    ]
